import { OpenSans } from "./config/fonts";
import "./globals.css";

export const metadata = {
  title: "Cowork",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`md:w-[95%] md:mx-auto w-full ${OpenSans.className}`}>
        {children}
      </body>
    </html>
  );
}
